"""empty message

Revision ID: fff0f8d9b93c
Revises: 
Create Date: 2025-03-31 22:47:14.500031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff0f8d9b93c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('data_json', sa.String(), nullable=False),
    sa.Column('article_link', sa.String(), nullable=False),
    sa.Column('article_date_published', sa.DateTime(), nullable=False),
    sa.Column('article_title', sa.String(), nullable=False),
    sa.Column('article_news_source', sa.String(), nullable=False),
    sa.Column('article_author', sa.String(), nullable=True),
    sa.Column('original_url', sa.String(), nullable=True),
    sa.Column('selected_for_display', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('llm_generated_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_link'),
    sa.UniqueConstraint('article_link', name='uq_article_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_items')
    # ### end Alembic commands ###
